name: rsapidata

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  getAndSaveData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        API_DATA_FILE: ./data/rsapidata.js
        ACTIONS_USER: ${{ secrets.ACTIONS_USER }}
        ACTIONS_EMAIL: ${{ secrets.ACTIONS_EMAIL }}
      run: |
        bash ./.github/scripts/rsapidata.sh
        git config --global user.name '${{ secrets.ACTIONS_USER }}'
        git config --global user.email '${{ secrets.ACTIONS_EMAIL }}'
        git commit -am "API Data fetch"
        git push